/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PostRequest =
  | {
      _csrf: string;
      email: string;
    }
  | {
      _csrf: string;
      password: string;
      reset_token: string;
    };
